import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "@/components/Layout/Main";
import HeadSection from "@/components/HeadSection";
import About from "@/components/About";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Education from "@/components/Education";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>

      <Layout>
        <HeadSection />
        <About />
        <Skills />
        <Projects />
        <Education />
      </Layout>
    </div>
  );
}
